# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-92ee5178-5c63-4db3-8941-9cd7b4d230aa";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-92ee5178-5c63-4db3-8941-9cd7b4d230aa".device = "/dev/disk/by-uuid/92ee5178-5c63-4db3-8941-9cd7b4d230aa";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/37A0-A359";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-9ad6c781-0d35-4693-ab97-2b66dd213065";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9ad6c781-0d35-4693-ab97-2b66dd213065".device = "/dev/disk/by-uuid/9ad6c781-0d35-4693-ab97-2b66dd213065";
  boot.initrd.luks.devices."luks-74ad8335-847d-42f9-8848-261e3c3d8e28".device = "/dev/disk/by-uuid/74ad8335-847d-42f9-8848-261e3c3d8e28";

  swapDevices =
    [ { device = "/dev/mapper/luks-74ad8335-847d-42f9-8848-261e3c3d8e28"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
